name: macOS

on:
  pull_request:
  push:
    branches:
      - master

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update toolchain
        run: rustup update --no-self-update stable
      - name: Add toolchain target
        run: rustup target add x86_64-pc-windows-gnu
      - name: Configure gnu
        run: brew install mingw-w64
      - name: Build
        run: cargo build --target x86_64-pc-windows-gnu
