name: Windows

on:
  pull_request:
  push:
    branches:
      - master

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: Test
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update toolchain
        run: rustup update --no-self-update stable
      - name: Add toolchain target
        run: rustup target add x86_64-pc-windows-gnu
      - name: Configure environment
        shell: pwsh
        run: |
          Add-Content $env:USERPROFILE\.cargo\config @"
              [target.x86_64-pc-windows-gnu]
              linker = `"C:\\msys64\\mingw64\\bin\\x86_64-w64-mingw32-gcc.exe`"
              ar = `"C:\\msys64\\mingw64\\bin\\ar.exe`"
              [target.i686-pc-windows-gnu]
              linker = `"C:\\msys64\\mingw32\\bin\\i686-w64-mingw32-gcc.exe`"
              ar = `"C:\\msys64\\mingw32\\bin\\ar.exe`"
          "@
          "C:\msys64\mingw64\bin" >> $env:GITHUB_PATH
          "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64" >> $env:GITHUB_PATH
          ((Resolve-Path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\*\bin\Hostx64\x64")
            | Sort-Object -Descending | Select -First 1).ToString() >> $env:GITHUB_PATH
          (Join-Path $env:GITHUB_WORKSPACE "target\debug\deps").ToString() >> $env:GITHUB_PATH
          (Join-Path $env:GITHUB_WORKSPACE "target\test\debug\deps").ToString() >> $env:GITHUB_PATH
          "INCLUDE=C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" `
            >> $env:GITHUB_ENV
      - name: Build
        run: cargo build --target x86_64-pc-windows-gnu
